server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/product_api
spring.datasource.username=postgres
spring.datasource.password=MartinDesarrollo28
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (opcional, para desarrollo)
spring.h2.console.enabled=true

# OpenAPI/Swagger
springdoc.api-docs.path=/api/docs


