server.port=8080

# File Storage Configuration
product.storage.file=data/products.json

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000

# Redis Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# OpenAPI/Swagger
springdoc.api-docs.path=/api/docs


